site_name: ProvesKit PySquared
site_description: "CircuitPython based Flight Software Library for the PROVES Kit."
site_url: https://docs.proveskit.space/
repo_url: https://github.com/proveskit/pysquared
repo_name: proveskit/pysquared
site_dir: site
watch: [mkdocs.yaml, README.md, docs/, circuitpython-workspaces/flight-software/src/pysquared/]

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Radio Test: radio-test.md
  - Design Guide: design-guide.md
  - Contributing Guide: contributing.md
  - API Reference: api.md
  - License: license.md


theme:
  name: material
  features:
  - content.action.edit
  - content.code.copy
  - content.code.select
  - content.tabs.link
  - header.autohide
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


plugins:
  - search  # To have search functionality on the document
  - autorefs
  - section-index
  - llmstxt:
      full_output: llms-full.txt
      sections:
        Home:
          - index.md
        Getting Started:
          - getting-started.md
        Radio Test:
          - radio-test.md
        Design Guide:
          - design-guide.md
        Contributing Guide:
          - contributing.md
        API Reference:
          - api.md
        License:
          - license.md
  - mkdocstrings:
        handlers:
          python:
            options:
              backlinks: tree
              docstring_options:
                ignore_init_summary: true
              docstring_section_style: list
              filters: ["!^_"]
              heading_level: 1
              inherited_members: true
              merge_init_into_class: true
              parameter_headings: true
              separate_signature: true
              show_root_heading: true
              show_root_full_path: false
              show_signature_annotations: true
              show_source: false
              show_symbol_type_heading: true
              show_symbol_type_toc: true
              signature_crossrefs: true
              summary: true
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      type: timeago
  - minify:
      minify_html: true

extra:
  social:
    - icon: material/github
      link: https://github.com/proveskit

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
