site_name: ProvesKit CirucuitPySquared
nav:
  - Home: index.md
  - Hardware Initialization:
      - Bus: busio.md
      - Decorators: decorators.md
      - Digitalio Pins: digitalio.md
  - Satellite Configuration: config.md
  - Satellite Functionalities:
      - Logging Functionality: logger.md
      - Sleep Functionality: sleep_helper.md
      - Detumbling Functionality: detumble.md
      - Radio Functionality:
          - Radio Configuration: radio.md
      - Watchdog: watchdog.md
      - Non Volatile Memory (NVM):
          - Boot Counter: counter.md
          - Bit Flags: flag.md
  - Communications:
      - Message Handling: cdh.md


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - header.autohide
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


plugins:
  - search  # To have search functionality on the document
  - mkdocstrings:
        handlers:
          python:
            paths: [pysquared/pysquared] # Location of code directory

extra:
  social:
    - icon: material/github
      link: https://github.com/proveskit


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
